title: 'pwn stories'
description: "yet another pwn blog."
baseurl: "/"
url: "https://divinepwner.github.io"

header_pages:
  - index.md
  - about.md
  - contact.md

style: light

footer: 'follow on <a href="https://twitter.com/divinepwner">twitter</a>'

# Build settings.....
markdown: kramdown
remote_theme: divinepwner/jekyll-theme-console
