title: 'pwn stories'
description: "yet another pwn blog."
baseurl: "/"
url: "https://divinepwner.github.io"

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

footer: 'follow on <a href="https://twitter.com/divinepwner">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
